### ISSUE TITLE
couple EOT files cannot be converted

### ISSUE THREAD

**Issue by mtayir** [umanwizard/libeot#4]
[font1.zip](https://github.com/umanwizard/libeot/files/4106738/font1.zip)
this is the eot file , it works good , but it cannot be ttf under libeot.

**Comment by mtayir** [comment]
@umanwizard problem is 
enum StreamResult sResult = parseOffsetTable(streams[0], &offsetTable);
right here

**Comment by umanwizard** [comment]
Thanks for the report. I will take a look this weekend.

**Comment by umanwizard** [comment]
@mtayir , I am able to extract the font using the latest code from git.

Can you tell me exactly what OS you are using and how you installed eot2ttf/libeot ?

**Comment by umanwizard** [comment]
eot2ttf on Ubuntu 18.04 also seems to work:

```
root@e1dd6d0114fb:/# file out.ttf^C
root@e1dd6d0114fb:/# eot2ttf font1.eot out.ttf
root@e1dd6d0114fb:/# file out.ttf
out.ttf: TrueType Font data, 17 tables, 1st "GDEF", 42 names, Unicode, Uyghur Computer Science Association. Free distributed and all rights reserved. http://www.ukij.
```

**Comment by mtayir** [comment]
@umanwizard thanks for replying , I am using Windows 10 , Dev C++ 5.11

**Comment by mtayir** [comment]
@umanwizard I'll try again

**Comment by umanwizard** [comment]
@mtayir Actually, I have never tested this on Windows... will try later and let you know if I can reproduce.

**Comment by mtayir** [comment]
@umanwizard Problem is solved. the problem is : I tried to unpack a not compressed fontdata. libeot works good in the windows right now! Thank you so much!

**Comment by umanwizard** [comment]
@mtayir I am glad it is working for you! Thanks for testing!
