### ISSUE TITLE
Couldn't allocate sufficient memory

### ISSUE THREAD

**Issue by hongnk** [umanwizard/libeot#7]
When built on MacOSX M1 (ARM), and tried a compressed .eot file, it resulted in "couldn't allocate sufficient memory". But it worked for non-compressed .eot file, so it must be something with the unpack function. 

However standard build on Ubuntu had no problem for both .eot files.

And my aim is to build as wasm (using emscripten), but it produced  the same memory error for compressed .eot when called in browser javascript (even on Ubuntu).

zip file contains sample compressed and uncompressed eot
[fonts.zip](https://github.com/umanwizard/libeot/files/15368165/fonts.zip)

**Comment by umanwizard** [comment]
Can you please share the font file that caused the issue On May 19, 2024, at 00:47, hongnk ***@***.***> wrote:﻿
When built on MacOSX M1 (ARM), and tried a compressed .eot file, it resulted in "couldn't allocate sufficient memory". But it worked for non-compressed .eot file, so it must be something with the unpack function.
However standard build on Ubuntu had no problem for both .eot files.
And my aim is to build as wasm (using emscripten), but it produced  the same memory error for compressed .eot when called in browser javascript (even on Ubuntu).

**Comment by hongnk** [comment]
Thanks for checking. Zip file contains sample compressed and uncompressed eot
[fonts.zip](https://github.com/umanwizard/libeot/files/15368165/fonts.zip)

**Comment by umanwizard** [comment]
Can you please describe exactly how you are building and running?

**Comment by hongnk** [comment]
Steps:
git clone https://github.com/umanwizard/libeot
cd libeot
autoreconf --install
./configure
make
then call ./eot2ttf [compressed eot] [out ttf]
![image](https://github.com/umanwizard/libeot/assets/5845263/f01364a0-0ef4-464b-96ac-3cf1ecb90afe)

**Comment by umanwizard** [comment]
Thank you for the help. I’ll investigate this soon.

**Comment by hongnk** [comment]
I have found that it is due to `gcc -O2`, changing it to `gcc -O1` works on Mac. This ticket can close. Thank you!

**Comment by umanwizard** [comment]
I've pushed a commit that should fix the issue even with -O3 or -O2. Please try again with latest master.

**Comment by hongnk** [comment]
Thank you it works perfectly! O2 helps reduce file size by half (vs O1). I'll try to use O3 although it doesn't improve further.
